alter table BXT_TEST_UNIT_01 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_01 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_01 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_02 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_02 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_02 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_03 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_03 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_03 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_04 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_04 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_04 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_05 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_05 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_05 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_06 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_06 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_06 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_07 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_07 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_07 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_08 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_08 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_08 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_09 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_09 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_09 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_10 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_10 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_10 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_11 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_11 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_11 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_12 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_12 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_12 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_13 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_13 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_13 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_14 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_14 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_14 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_15 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_15 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_15 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_16 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_16 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_16 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_17 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_17 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_17 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_18 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_18 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_18 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_19 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_19 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_19 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_20 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_20 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_20 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_21 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_21 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_21 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_22 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_22 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_22 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_23 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_23 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_23 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_24 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_24 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_24 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_25 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_25 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_25 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_26 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_26 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_26 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_27 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_27 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_27 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_28 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_28 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_28 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_29 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_29 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_29 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_30 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_30 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_30 ADD( MAX_ELAPSED_SEC NUMBER(8) );

alter table BXT_TEST_UNIT_31 ADD( CALLER_LINE_NO NUMBER(8) );
alter table BXT_TEST_UNIT_31 ADD( MIN_ELAPSED_SEC NUMBER(8) );
alter table BXT_TEST_UNIT_31 ADD( MAX_ELAPSED_SEC NUMBER(8) );


