/* 테스트 유닛 익셉션 오브젝트 */
CREATE TABLE BXT_TEST_UNIT_EXCEPTION (
	TEST_UNIT_UID VARCHAR2(32) NOT NULL, /* 테스트 유닛 UID */
	SYS_ID VARCHAR2(16) NOT NULL, /* 시스템 ID */
	EXCEPTION_QN VARCHAR2(1000) NOT NULL, /* 익셉션 퀄리파이드네임 */
	CATCH_YN VARCHAR2(1) NOT NULL, /* CATCH 여부 */
	EXCEPTION_MSG VARCHAR2(4000), /* 익셉션 메시지 */
	OBJECT_DATA BLOB, /* 오브젝트데이터 */
	BASE_DATE VARCHAR2(8) NOT NULL, /* 기준일자 */
	REG_DTTM VARCHAR2(23) NOT NULL /* 등록 일시 */
);

COMMENT ON TABLE BXT_TEST_UNIT_EXCEPTION IS '테스트 유닛 익셉션 오브젝트';
COMMENT ON COLUMN BXT_TEST_UNIT_EXCEPTION.TEST_UNIT_UID IS '테스트 유닛 UID';
COMMENT ON COLUMN BXT_TEST_UNIT_EXCEPTION.SYS_ID IS '시스템 ID';
COMMENT ON COLUMN BXT_TEST_UNIT_EXCEPTION.EXCEPTION_QN IS '익셉션 퀄리파이드네임';
COMMENT ON COLUMN BXT_TEST_UNIT_EXCEPTION.CATCH_YN IS 'CATCH 여부';
COMMENT ON COLUMN BXT_TEST_UNIT_EXCEPTION.EXCEPTION_MSG IS '익셉션 메시지';
COMMENT ON COLUMN BXT_TEST_UNIT_EXCEPTION.OBJECT_DATA IS '오브젝트데이터';
COMMENT ON COLUMN BXT_TEST_UNIT_EXCEPTION.BASE_DATE IS '기준일자';
COMMENT ON COLUMN BXT_TEST_UNIT_EXCEPTION.REG_DTTM IS '등록 일시';

CREATE UNIQUE INDEX PK_BXT_TEST_UNIT_EXCEPTION
	ON BXT_TEST_UNIT_EXCEPTION (
		TEST_UNIT_UID ASC
	);

ALTER TABLE BXT_TEST_UNIT_EXCEPTION
	ADD
		CONSTRAINT PK_BXT_TEST_UNIT_EXCEPTION
		PRIMARY KEY (
			TEST_UNIT_UID
		);