/* 테스트 유닛 오브젝트 */
CREATE TABLE BXT_TEST_UNIT_OBJECT (
	TEST_UNIT_UID VARCHAR2(32) NOT NULL, /* 테스트 유닛 UID */
	OBJECT_CD VARCHAR2(1) NOT NULL, /* 오브젝트 코드 */
	OBJECT_SEQ NUMBER(8) NOT NULL, /* 오브젝트 순번 */
	SYS_ID VARCHAR2(16) NOT NULL, /* 시스템 ID */
	OBJECT_QN VARCHAR2(1000), /* 오브젝트 퀄리파이드네임 */
	SIZE_EXCEED_YN VARCHAR2(1), /* 사이즈 초과 여부 */
	OBJECT_DATA BLOB, /* 오브젝트데이터 */
	BASE_DATE VARCHAR2(8) NOT NULL, /* 기준일자 */
	REG_DTTM VARCHAR2(23) NOT NULL /* 등록 일시 */
);

COMMENT ON TABLE BXT_TEST_UNIT_OBJECT IS '테스트 유닛 오브젝트';
COMMENT ON COLUMN BXT_TEST_UNIT_OBJECT.TEST_UNIT_UID IS '테스트 유닛 UID';
COMMENT ON COLUMN BXT_TEST_UNIT_OBJECT.OBJECT_CD IS '오브젝트 코드';
COMMENT ON COLUMN BXT_TEST_UNIT_OBJECT.OBJECT_SEQ IS '오브젝트 순번';
COMMENT ON COLUMN BXT_TEST_UNIT_OBJECT.SYS_ID IS '시스템 ID';
COMMENT ON COLUMN BXT_TEST_UNIT_OBJECT.OBJECT_QN IS '오브젝트 퀄리파이드네임';
COMMENT ON COLUMN BXT_TEST_UNIT_OBJECT.SIZE_EXCEED_YN IS '사이즈 초과 여부';
COMMENT ON COLUMN BXT_TEST_UNIT_OBJECT.OBJECT_DATA IS '오브젝트데이터';
COMMENT ON COLUMN BXT_TEST_UNIT_OBJECT.BASE_DATE IS '기준일자';
COMMENT ON COLUMN BXT_TEST_UNIT_OBJECT.REG_DTTM IS '등록 일시';

CREATE UNIQUE INDEX PK_BXT_TEST_UNIT_OBJECT
	ON BXT_TEST_UNIT_OBJECT (
		TEST_UNIT_UID ASC,
		OBJECT_CD ASC,
		OBJECT_SEQ ASC
	);

ALTER TABLE BXT_TEST_UNIT_OBJECT
	ADD
		CONSTRAINT PK_BXT_TEST_UNIT_OBJECT
		PRIMARY KEY (
			TEST_UNIT_UID,
			OBJECT_CD,
			OBJECT_SEQ
		);

