
/* 테스트 유닛 실행라인 */
CREATE TABLE BXT_TEST_UNIT_EXEC_LINE (
	TEST_UNIT_UID VARCHAR2(32) NOT NULL, /* 테스트 유닛 UID */
	SEQ NUMBER(8) NOT NULL, /* 일련번호 */
	SYS_ID VARCHAR2(16) NOT NULL, /* 시스템 ID */
	LINE_DATA VARCHAR2(4000), /* 라인 데이터 */
	BASE_DATE VARCHAR2(8) NOT NULL, /* 기준일자 */
	REG_DTTM VARCHAR2(23) NOT NULL /* 등록 일시 */
);

COMMENT ON TABLE BXT_TEST_UNIT_EXEC_LINE IS '테스트 유닛 실행라인';
COMMENT ON COLUMN BXT_TEST_UNIT_EXEC_LINE.TEST_UNIT_UID IS '테스트 유닛 UID';
COMMENT ON COLUMN BXT_TEST_UNIT_EXEC_LINE.SEQ IS '일련번호';
COMMENT ON COLUMN BXT_TEST_UNIT_EXEC_LINE.SYS_ID IS '시스템 ID';
COMMENT ON COLUMN BXT_TEST_UNIT_EXEC_LINE.LINE_DATA IS '라인 데이터';
COMMENT ON COLUMN BXT_TEST_UNIT_EXEC_LINE.BASE_DATE IS '기준일자';
COMMENT ON COLUMN BXT_TEST_UNIT_EXEC_LINE.REG_DTTM IS '등록 일시';

CREATE UNIQUE INDEX PK_BXT_TEST_UNIT_EXEC_LINE
	ON BXT_TEST_UNIT_EXEC_LINE (
		TEST_UNIT_UID ASC,
		SEQ ASC
	);

ALTER TABLE BXT_TEST_UNIT_EXEC_LINE
	ADD
		CONSTRAINT PK_BXT_TEST_UNIT_EXEC_LINE
		PRIMARY KEY (
			TEST_UNIT_UID,
			SEQ
		);
